//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Remesa
    {
        public int IDPACIENTE { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public string NOMBRE_Y_APELLIDOS { get; set; }
        public string CUENTA_BANCO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
